# should be run using the run_linux script
# to manage the xauth (x11 server authentification)

version: '2.16'

services:
  novnc:
    image: 'theasp/novnc:latest'
    container_name: novnc
    hostname: novnc
    environment:
      - DISPLAY_WIDTH=3000
      - DISPLAY_HEIGHT=1800
      - RUN_XTERM=no
    ports:
      - '8080:8080'
    network_mode: ros_netw

  ros2:
    image: ros2:user
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: ros2
    hostname: ros2
    extra_hosts:
        - "ros2:127.0.0.1"
    volumes:
      - ../wdir:/home/docker/wdir
    environment:
      - DISPLAY=novnc:0.0
      - XDG_RUNTIME_DIR=/tmp/runtime-docker
      - QT_X11_NO_MITSHM=1
    network_mode: ros_netw
    working_dir: /home/docker/wdir
    command: bash
    # privileged: true
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    # group_add:
    #   - "dialout"

